#! /usr/bin/env perl

use strict;
use warnings;

use EV;
use Mojolicious::Lite;
use lib 'lib';
use Cyborg;
use CyborgRally;
use JSON;

my $json = JSON->new;
my $game = new CyborgRally;

get '/' => sub {
    shift->reply->static('index.html');
};

websocket '/websocket' => sub {
    my $c = shift;
    $c->inactivity_timeout(300);

    my $cyborg = Cyborg->new($c);
    $game->on_connect($cyborg); 

    $c->on(
        message => sub {
            my ( $c, $msg ) = @_;
            $game->on_message($cyborg, $json->decode($msg));
        }
    );

    $c->on(
        finish => sub {
            $game->on_disconnect($cyborg);
        }
    );
};

if (!$INC{'Mojo/Server/Morbo.pm'}) {
    Mojo::Server::Daemon->new( app => app, listen => ['http://*:3000'] )->run;
}
else {
    app->start;
}
